import { AddIcon } from '@chakra-ui/icons'
import { Button, Container } from '@chakra-ui/react'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { getCars } from '../api/getCars'
import CarsList from '../components/CarsList'
import styles from '../styles/Home.module.css'


export default function Home ({ cars }: InferGetStaticPropsType<typeof getStaticProps>) {

  return (
    <>
      <Head>
        <title>MBFS Cars Inventory</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>
      <main className={styles.main}>
        <Container maxWidth={'100%'}>
          <Link href={'/create'}>
            <Button colorScheme={'teal'} my={'4'}><AddIcon/>&nbsp;New Car</Button>
          </Link>
          <CarsList cars={cars}/>
        </Container>
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const cars = await getCars()

  return {
    props: {
      cars
    },
    revalidate: true // TODO nějakej čas
  }
}
