import { Container } from '@chakra-ui/react'
import { InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import getCars from './api/getCars'
import CarsList from '../components/CarsList'
import styles from '../styles/Home.module.css'

export default function Home({
  cars
}: InferGetStaticPropsType<typeof getStaticProps>) {

  return (
    <>
      <Head>
        <title>MBFS Cars Inventory</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Container maxWidth={'100%'}>
          <CarsList cars={cars} />
        </Container>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const cars = await getCars()

  return {
    props: {
      cars
    }
  }
}
